#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The Nikasha Authors
# SPDX-License-Identifier: CC-BY-4.0
"""Generate ``docs/checks.md`` from the check registry (SPEC §12).

The catalogue is generated rather than written by hand so it can never drift from the
code: every check's ID, name, group, claim kinds and strengths come from the registry and
from ``lr_defaults.yaml``. CI regenerates it and fails if the working copy differs.

Usage:
    python scripts/gen_checks_doc.py            # write docs/checks.md
    python scripts/gen_checks_doc.py --check    # exit 1 if it is out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from nikasha.checks import load_checks  # noqa: E402
from nikasha.checks.strengths import default_strengths  # noqa: E402

OUTPUT = ROOT / "docs" / "checks.md"

HEADER = """<!--
SPDX-FileCopyrightText: 2026 The Nikasha Authors
SPDX-License-Identifier: CC-BY-4.0
-->

# Checks catalogue

<!-- Generated by scripts/gen_checks_doc.py. Do not edit by hand. -->

Every check answers one factual question about a report's claims against the repository at
the resolved commit, and returns evidence carrying a natural-log likelihood ratio
(SPEC §12). Strengths below are the **initial priors** from
`src/nikasha/checks/lr_defaults.yaml`; calibration (SPEC §14.2) replaces them, and the
table actually used is recorded in every result.

Two rules hold for every check:

- **Only `project_attributed`, non-negated claims may be refuted** (ADR 0003). The
  framework enforces this, so a finding about a reporter's own PoC or a third-party API is
  reported without counting against the report.
- **Absence is never proof** (P4). When history is incomplete, a file did not parse
  cleanly, or a path is generated, a check reports uncertainty rather than a refutation.

"""


def build() -> str:
    checks = load_checks()
    strengths = default_strengths()
    lines = [HEADER, "## Summary\n", "| ID | Name | Group | Applies to |", "|---|---|---|---|"]
    for key in sorted(checks):
        check = checks[key]
        kinds = ", ".join(f"`{k}`" for k in sorted(check.applies_to)) or "—"
        lines.append(
            f"| [{check.id}](#{check.id.lower()}) | {check.name} | `{check.group}` | {kinds} |"
        )
    lines.append("")

    for key in sorted(checks):
        check = checks[key]
        description = getattr(check, "description", "") or ""
        lines.append(f"## {check.id}")
        lines.append("")
        lines.append(f"**{check.name}** · group `{check.group}`")
        lines.append("")
        if description:
            lines.append(description)
            lines.append("")
        kinds = ", ".join(f"`{k}`" for k in sorted(check.applies_to)) or "—"
        lines.append(f"Applies to: {kinds}")
        lines.append("")
        outcomes = strengths.outcomes(check.id)
        if outcomes:
            lines.append("| Outcome | Strength |")
            lines.append("|---|---|")
            for name in sorted(outcomes):
                value = outcomes[name]
                lines.append(f"| `{name}` | {value:+.2f} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Exit 1 if docs/checks.md is out of date."
    )
    args = parser.parse_args()
    generated = build()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            print(
                f"error: {OUTPUT.relative_to(ROOT)} is out of date; run scripts/gen_checks_doc.py"
            )
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
