#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The Nikasha Authors
# SPDX-License-Identifier: CC-BY-4.0
"""Generate ``docs/checks.md`` from the check registry (SPEC §12).

The catalogue is generated rather than written by hand so it can never drift from the
code: every check's ID, name, group, claim kinds and strengths come from the registry and
from ``lr_defaults.yaml``. CI regenerates it and fails if the working copy differs.

Usage:
    python scripts/gen_checks_doc.py            # write docs/checks.md
    python scripts/gen_checks_doc.py --check    # exit 1 if it is out of date
"""

from __future__ import annotations

import argparse
import ast
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from nikasha.checks import load_checks  # noqa: E402
from nikasha.checks.strengths import default_strengths  # noqa: E402

OUTPUT = ROOT / "docs" / "checks.md"

HEADER = """<!--
SPDX-FileCopyrightText: 2026 The Nikasha Authors
SPDX-License-Identifier: CC-BY-4.0
-->

# Checks catalogue

<!-- Generated by scripts/gen_checks_doc.py. Do not edit by hand. -->

Every check answers one factual question about a report's claims against the repository at
the resolved commit, and returns evidence carrying a natural-log likelihood ratio
(SPEC §12). Strengths below are the **initial priors** from
`src/nikasha/checks/lr_defaults.yaml`; calibration (SPEC §14.2) replaces them, and the
table actually used is recorded in every result.

Two rules hold for every check:

- **Only `project_attributed`, non-negated claims may be refuted** (ADR 0003). The
  framework enforces this, so a finding about a reporter's own PoC or a third-party API is
  reported without counting against the report.
- **Absence is never proof** (P4). When history is incomplete, a file did not parse
  cleanly, or a path is generated, a check reports uncertainty rather than a refutation.

Each check lists every outcome key it can record: the scored ones from the strengths table,
and the ones read statically from its source. Outcomes marked *not scored* are NEUTRAL or
ERROR results that move no score.

"""


#: A judgement tuple is ``(outcome, key, ...)``.
_MIN_JUDGEMENT = 2
_OUTCOME_KINDS = frozenset({"SUPPORTS", "REFUTES", "NEUTRAL", "ERROR"})


def _literals(node: ast.expr | None, consts: dict[str, str]) -> set[str]:
    """String values ``node`` can take: a literal, a module constant, or a ternary of them."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return {node.value}
    if isinstance(node, ast.Name) and node.id in consts:
        return {consts[node.id]}
    if isinstance(node, ast.IfExp):
        return _literals(node.body, consts) | _literals(node.orelse, consts)
    if isinstance(node, ast.BoolOp):
        return set().union(*(_literals(v, consts) for v in node.values))
    return set()


def _module_constants(tree: ast.Module) -> dict[str, str]:
    consts: dict[str, str] = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            value, targets = node.value, node.targets
        elif isinstance(node, ast.AnnAssign):
            value, targets = node.value, [node.target]
        else:
            continue
        if not (isinstance(value, ast.Constant) and isinstance(value.value, str)):
            continue
        for target in targets:
            if isinstance(target, ast.Name):
                consts[target.id] = value.value
    return consts


def emitted_outcomes(source: str) -> set[str]:
    """Outcome keys a check module records, found statically in its source.

    Many outcomes (the NEUTRAL ones above all) carry no strength and so never appear in
    ``lr_defaults.yaml``; reading them from the code keeps the catalogue complete without a
    hand-written list. Recognised forms: ``{"outcome": X}``, ``d["outcome"] = X``,
    ``label=X`` keyword arguments, ``("NEUTRAL", X, ...)`` judgement tuples, and
    ``{"status": ("NEUTRAL", None)}`` tables whose key is the recorded outcome.
    """
    tree = ast.parse(source)
    consts = _module_constants(tree)
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Dict):
            for key, value in zip(node.keys, node.values, strict=True):
                if isinstance(key, ast.Constant) and key.value == "outcome":
                    found |= _literals(value, consts)
                if (
                    isinstance(value, ast.Tuple)
                    and len(value.elts) >= _MIN_JUDGEMENT
                    and isinstance(value.elts[0], ast.Constant)
                    and value.elts[0].value in _OUTCOME_KINDS
                    and isinstance(value.elts[1], ast.Constant)
                    and value.elts[1].value is None
                ):
                    found |= _literals(key, consts)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if (
                    isinstance(target, ast.Subscript)
                    and isinstance(target.slice, ast.Constant)
                    and target.slice.value == "outcome"
                ):
                    found |= _literals(node.value, consts)
        elif isinstance(node, ast.keyword) and node.arg == "label":
            found |= _literals(node.value, consts)
        elif (
            isinstance(node, ast.Tuple)
            and len(node.elts) >= _MIN_JUDGEMENT
            and isinstance(node.elts[0], ast.Constant)
            and node.elts[0].value in _OUTCOME_KINDS
        ):
            found |= _literals(node.elts[1], consts)
    return found


def build() -> str:
    checks = load_checks()
    strengths = default_strengths()
    lines = [HEADER, "## Summary\n", "| ID | Name | Group | Applies to |", "|---|---|---|---|"]
    for key in sorted(checks):
        check = checks[key]
        kinds = ", ".join(f"`{k}`" for k in sorted(check.applies_to)) or "—"
        lines.append(
            f"| [{check.id}](#{check.id.lower()}) | {check.name} | `{check.group}` | {kinds} |"
        )
    lines.append("")

    for key in sorted(checks):
        check = checks[key]
        description = getattr(check, "description", "") or ""
        lines.append(f"## {check.id}")
        lines.append("")
        lines.append(f"**{check.name}** · group `{check.group}`")
        lines.append("")
        if description:
            lines.append(description)
            lines.append("")
        kinds = ", ".join(f"`{k}`" for k in sorted(check.applies_to)) or "—"
        lines.append(f"Applies to: {kinds}")
        lines.append("")
        outcomes = strengths.outcomes(check.id)
        emitted = emitted_outcomes(inspect.getsource(sys.modules[type(check).__module__]))
        names = set(outcomes) | emitted
        if names:
            lines.append("| Outcome | Strength |")
            lines.append("|---|---|")
            for name in sorted(names):
                value = f"{outcomes[name]:+.2f}" if name in outcomes else "— (not scored)"
                lines.append(f"| `{name}` | {value} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Exit 1 if docs/checks.md is out of date."
    )
    args = parser.parse_args()
    generated = build()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            print(
                f"error: {OUTPUT.relative_to(ROOT)} is out of date; run scripts/gen_checks_doc.py"
            )
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
