# SPDX-FileCopyrightText: 2026 The Nikasha Authors
# SPDX-License-Identifier: Apache-2.0
"""Typed, immutable data models shared by every pipeline stage (SPEC §7)."""

from nikasha.model.claims import (
    BehaviorClaim,
    Claim,
    ClaimKind,
    FileClaim,
    Frame,
    ImpactClaim,
    LineClaim,
    MemoryAccess,
    MemoryRegion,
    OptionClaim,
    PatchClaim,
    PatchHunk,
    PatchLine,
    Permalink,
    PocClaim,
    ReferenceClaim,
    SnippetClaim,
    Stack,
    SymbolClaim,
    TraceClaim,
    TraceData,
    VersionClaim,
    VersionSpec,
)
from nikasha.model.evidence import CodeLocation, CommandRecord, Evidence
from nikasha.model.report import (
    Attachment,
    CodeBlock,
    DeclaredTarget,
    Report,
    ReportSource,
    SourceMap,
    SourceSegment,
    Span,
)
from nikasha.model.result import Environment, ResolvedTarget, Result
from nikasha.model.verdict import Question, Verdict

__all__ = [
    "Attachment",
    "BehaviorClaim",
    "Claim",
    "ClaimKind",
    "CodeBlock",
    "CodeLocation",
    "CommandRecord",
    "DeclaredTarget",
    "Environment",
    "Evidence",
    "FileClaim",
    "Frame",
    "ImpactClaim",
    "LineClaim",
    "MemoryAccess",
    "MemoryRegion",
    "OptionClaim",
    "PatchClaim",
    "PatchHunk",
    "PatchLine",
    "Permalink",
    "PocClaim",
    "Question",
    "ReferenceClaim",
    "Report",
    "ReportSource",
    "ResolvedTarget",
    "Result",
    "SnippetClaim",
    "SourceMap",
    "SourceSegment",
    "Span",
    "Stack",
    "SymbolClaim",
    "TraceClaim",
    "TraceData",
    "Verdict",
    "VersionClaim",
    "VersionSpec",
]
